"""Persistence for the research bot using Neon PostgreSQL or local SQLite."""

import json
import logging
import os
import sqlite3
from contextlib import contextmanager
from typing import List, Optional

import config
from src.exceptions import DatabaseError
from src.models import Article, StoredArticle

logger = logging.getLogger(__name__)

SQLITE_SCHEMA = (
    """
    CREATE TABLE IF NOT EXISTS articles (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        page_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        summary TEXT,
        url TEXT,
        categories TEXT,
        word_count INTEGER DEFAULT 0,
        source TEXT DEFAULT 'wikipedia',
        fetched_at TEXT NOT NULL,
        UNIQUE(page_id, source)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_articles_title ON articles(title)",
    "CREATE INDEX IF NOT EXISTS idx_articles_fetched_at ON articles(fetched_at)",
    """
    CREATE TABLE IF NOT EXISTS search_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        query TEXT NOT NULL,
        result_count INTEGER DEFAULT 0,
        searched_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
    """,
)

POSTGRES_SCHEMA = (
    """
    CREATE TABLE IF NOT EXISTS articles (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        page_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        summary TEXT,
        url TEXT,
        categories TEXT,
        word_count INTEGER DEFAULT 0,
        source TEXT DEFAULT 'wikipedia',
        fetched_at TEXT NOT NULL,
        UNIQUE(page_id, source)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_articles_title ON articles(title)",
    "CREATE INDEX IF NOT EXISTS idx_articles_fetched_at ON articles(fetched_at)",
    """
    CREATE TABLE IF NOT EXISTS search_log (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        query TEXT NOT NULL,
        result_count INTEGER DEFAULT 0,
        searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
)


class ResearchDatabase:
    """Store articles in Neon when DATABASE_URL is configured, otherwise SQLite."""

    def __init__(
        self,
        db_path: Optional[str] = None,
        database_url: Optional[str] = None,
    ):
        self.database_url = database_url or (None if db_path else config.DATABASE_URL)
        self.db_path = db_path or config.DATABASE_PATH
        if not self.database_url:
            os.makedirs(os.path.dirname(self.db_path) or ".", exist_ok=True)
        self._init_schema()

    @property
    def backend(self) -> str:
        return "postgresql" if self.database_url else "sqlite"

    @contextmanager
    def _connect(self):
        if self.database_url:
            try:
                import psycopg
                from psycopg.rows import dict_row

                conn = psycopg.connect(self.database_url, row_factory=dict_row)
            except Exception as exc:
                raise DatabaseError(f"Could not connect to PostgreSQL: {exc}") from exc
            try:
                yield conn
                conn.commit()
            except psycopg.Error as exc:
                conn.rollback()
                raise DatabaseError(f"Database operation failed: {exc}") from exc
            finally:
                conn.close()
            return

        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        try:
            yield conn
            conn.commit()
        except sqlite3.Error as exc:
            conn.rollback()
            raise DatabaseError(f"Database operation failed: {exc}") from exc
        finally:
            conn.close()

    def _init_schema(self) -> None:
        try:
            with self._connect() as conn:
                statements = POSTGRES_SCHEMA if self.database_url else SQLITE_SCHEMA
                for statement in statements:
                    conn.execute(statement)
        except DatabaseError:
            raise
        except Exception as exc:
            raise DatabaseError(f"Failed to initialize schema: {exc}") from exc

    def _parameters(self, sql: str) -> str:
        return sql.replace("?", "%s") if self.database_url else sql

    # -- writes ------------------------------------------------------------

    def save_article(self, article: Article) -> int:
        """Insert an article, or update it if the same page was already stored."""
        with self._connect() as conn:
            conn.execute(
                self._parameters(
                    """
                    INSERT INTO articles
                        (page_id, title, summary, url, categories, word_count, source, fetched_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT(page_id, source) DO UPDATE SET
                        title=excluded.title,
                        summary=excluded.summary,
                        url=excluded.url,
                        categories=excluded.categories,
                        word_count=excluded.word_count,
                        fetched_at=excluded.fetched_at
                    """
                ),
                (
                    article.page_id,
                    article.title,
                    article.summary,
                    article.url,
                    json.dumps(article.categories),
                    article.word_count,
                    article.source,
                    article.fetched_at,
                ),
            )
            row = conn.execute(
                self._parameters(
                    "SELECT id FROM articles WHERE page_id = ? AND source = ?"
                ),
                (article.page_id, article.source),
            ).fetchone()
            return row["id"] if row else -1

    def log_search(self, query: str, result_count: int) -> None:
        with self._connect() as conn:
            conn.execute(
                self._parameters(
                    "INSERT INTO search_log (query, result_count) VALUES (?, ?)"
                ),
                (query, result_count),
            )

    # -- reads -------------------------------------------------------------

    def get_by_title(self, title: str) -> Optional[StoredArticle]:
        with self._connect() as conn:
            sql = (
                "SELECT * FROM articles WHERE LOWER(title) = LOWER(?)"
                if self.database_url
                else "SELECT * FROM articles WHERE title = ? COLLATE NOCASE"
            )
            row = conn.execute(self._parameters(sql), (title,)).fetchone()
            return _row_to_article(row) if row else None

    def search_stored(self, keyword: str, limit: int = 20) -> List[StoredArticle]:
        pattern = f"%{keyword}%"
        with self._connect() as conn:
            rows = conn.execute(
                self._parameters(
                    """
                    SELECT * FROM articles
                    WHERE title LIKE ? OR summary LIKE ?
                    ORDER BY fetched_at DESC
                    LIMIT ?
                    """
                ),
                (pattern, pattern, limit),
            ).fetchall()
            return [_row_to_article(row) for row in rows]

    def list_recent(self, limit: int = 10) -> List[StoredArticle]:
        with self._connect() as conn:
            rows = conn.execute(
                self._parameters(
                    "SELECT * FROM articles ORDER BY fetched_at DESC LIMIT ?"
                ),
                (limit,),
            ).fetchall()
            return [_row_to_article(row) for row in rows]

    def delete_article(self, page_id: int) -> bool:
        with self._connect() as conn:
            cursor = conn.execute(
                self._parameters("DELETE FROM articles WHERE page_id = ?"),
                (page_id,),
            )
            return cursor.rowcount > 0

    def count(self) -> int:
        with self._connect() as conn:
            row = conn.execute("SELECT COUNT(*) AS c FROM articles").fetchone()
            return row["c"]


def _row_to_article(row) -> StoredArticle:
    return StoredArticle(
        record_id=row["id"],
        page_id=row["page_id"],
        title=row["title"],
        summary=row["summary"] or "",
        url=row["url"] or "",
        categories=json.loads(row["categories"] or "[]"),
        word_count=row["word_count"] or 0,
        source=row["source"] or "wikipedia",
        fetched_at=row["fetched_at"],
    )