"""Persistence for the research bot using Neon PostgreSQL or local SQLite."""

import json
import logging
import math
import os
import sqlite3
from contextlib import contextmanager
from typing import List, Optional

import config
from src.exceptions import DatabaseError
from src.models import Article, StoredArticle

logger = logging.getLogger(__name__)

SQLITE_SCHEMA = (
    """
    CREATE TABLE IF NOT EXISTS articles (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        page_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        summary TEXT,
        content TEXT,
        url TEXT,
        categories TEXT,
        word_count INTEGER DEFAULT 0,
        source TEXT DEFAULT 'wikipedia',
        fetched_at TEXT NOT NULL,
        UNIQUE(page_id, source)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_articles_title ON articles(title)",
    "CREATE INDEX IF NOT EXISTS idx_articles_fetched_at ON articles(fetched_at)",
    """
    CREATE TABLE IF NOT EXISTS article_embeddings (
        article_id INTEGER PRIMARY KEY REFERENCES articles(id) ON DELETE CASCADE,
        embedding TEXT NOT NULL,
        model TEXT NOT NULL,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS search_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        query TEXT NOT NULL,
        result_count INTEGER DEFAULT 0,
        searched_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
    """,
)

POSTGRES_SCHEMA = (
    "CREATE EXTENSION IF NOT EXISTS vector",
    """
    CREATE TABLE IF NOT EXISTS articles (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        page_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        summary TEXT,
        content TEXT,
        url TEXT,
        categories TEXT,
        word_count INTEGER DEFAULT 0,
        source TEXT DEFAULT 'wikipedia',
        fetched_at TEXT NOT NULL,
        UNIQUE(page_id, source)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_articles_title ON articles(title)",
    "CREATE INDEX IF NOT EXISTS idx_articles_fetched_at ON articles(fetched_at)",
    f"""
    CREATE TABLE IF NOT EXISTS article_embeddings (
        article_id INTEGER PRIMARY KEY REFERENCES articles(id) ON DELETE CASCADE,
        embedding vector({config.EMBEDDING_DIMENSIONS}) NOT NULL,
        model TEXT NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_article_embeddings_vector ON article_embeddings USING hnsw (embedding vector_cosine_ops)",
    """
    CREATE TABLE IF NOT EXISTS search_log (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        query TEXT NOT NULL,
        result_count INTEGER DEFAULT 0,
        searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
)


class ResearchDatabase:
    """Store articles in Neon when DATABASE_URL is configured, otherwise SQLite."""

    def __init__(
        self,
        db_path: Optional[str] = None,
        database_url: Optional[str] = None,
    ):
        self.database_url = database_url or (None if db_path else config.DATABASE_URL)
        self.db_path = db_path or config.DATABASE_PATH
        if not self.database_url:
            os.makedirs(os.path.dirname(self.db_path) or ".", exist_ok=True)
        self._init_schema()

    @property
    def backend(self) -> str:
        return "postgresql" if self.database_url else "sqlite"

    @contextmanager
    def _connect(self):
        if self.database_url:
            try:
                import psycopg
                from psycopg.rows import dict_row

                conn = psycopg.connect(self.database_url, row_factory=dict_row)
            except Exception as exc:
                raise DatabaseError(f"Could not connect to PostgreSQL: {exc}") from exc
            try:
                yield conn
                conn.commit()
            except psycopg.Error as exc:
                conn.rollback()
                raise DatabaseError(f"Database operation failed: {exc}") from exc
            finally:
                conn.close()
            return

        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        try:
            yield conn
            conn.commit()
        except sqlite3.Error as exc:
            conn.rollback()
            raise DatabaseError(f"Database operation failed: {exc}") from exc
        finally:
            conn.close()

    def _init_schema(self) -> None:
        try:
            with self._connect() as conn:
                statements = POSTGRES_SCHEMA if self.database_url else SQLITE_SCHEMA
                for statement in statements:
                    conn.execute(statement)
                # Keep databases created before RAG support usable.
                if self.database_url:
                    conn.execute(
                        "ALTER TABLE articles ADD COLUMN IF NOT EXISTS content TEXT"
                    )
                else:
                    columns = conn.execute("PRAGMA table_info(articles)").fetchall()
                    if not any(column[1] == "content" for column in columns):
                        conn.execute("ALTER TABLE articles ADD COLUMN content TEXT")
        except DatabaseError:
            raise
        except Exception as exc:
            raise DatabaseError(f"Failed to initialize schema: {exc}") from exc

    def _parameters(self, sql: str) -> str:
        return sql.replace("?", "%s") if self.database_url else sql

    # -- writes ------------------------------------------------------------

    def save_article(self, article: Article) -> int:
        """Insert an article, or update it if the same page was already stored."""
        with self._connect() as conn:
            conn.execute(
                self._parameters(
                    """
                    INSERT INTO articles
                        (page_id, title, summary, content, url, categories, word_count, source, fetched_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ON CONFLICT(page_id, source) DO UPDATE SET
                        title=excluded.title,
                        summary=excluded.summary,
                        content=excluded.content,
                        url=excluded.url,
                        categories=excluded.categories,
                        word_count=excluded.word_count,
                        fetched_at=excluded.fetched_at
                    """
                ),
                (
                    article.page_id,
                    article.title,
                    article.summary,
                    article.content,
                    article.url,
                    json.dumps(article.categories),
                    article.word_count,
                    article.source,
                    article.fetched_at,
                ),
            )
            row = conn.execute(
                self._parameters(
                    "SELECT id FROM articles WHERE page_id = ? AND source = ?"
                ),
                (article.page_id, article.source),
            ).fetchone()
            return row["id"] if row else -1

    def save_embedding(self, article_id: int, embedding: List[float], model: str) -> None:
        """Persist an article embedding in pgvector or SQLite test storage."""
        vector = "[" + ",".join(str(value) for value in embedding) + "]"
        with self._connect() as conn:
            if self.database_url:
                conn.execute(
                    """
                    INSERT INTO article_embeddings (article_id, embedding, model)
                    VALUES (%s, %s::vector, %s)
                    ON CONFLICT(article_id) DO UPDATE SET
                        embedding=excluded.embedding,
                        model=excluded.model,
                        updated_at=CURRENT_TIMESTAMP
                    """,
                    (article_id, vector, model),
                )
            else:
                conn.execute(
                    """
                    INSERT INTO article_embeddings (article_id, embedding, model)
                    VALUES (?, ?, ?)
                    ON CONFLICT(article_id) DO UPDATE SET
                        embedding=excluded.embedding,
                        model=excluded.model,
                        updated_at=CURRENT_TIMESTAMP
                    """,
                    (article_id, json.dumps(embedding), model),
                )

    def log_search(self, query: str, result_count: int) -> None:
        with self._connect() as conn:
            conn.execute(
                self._parameters(
                    "INSERT INTO search_log (query, result_count) VALUES (?, ?)"
                ),
                (query, result_count),
            )

    # -- reads -------------------------------------------------------------

    def get_by_title(self, title: str) -> Optional[StoredArticle]:
        with self._connect() as conn:
            sql = (
                "SELECT * FROM articles WHERE LOWER(title) = LOWER(?)"
                if self.database_url
                else "SELECT * FROM articles WHERE title = ? COLLATE NOCASE"
            )
            row = conn.execute(self._parameters(sql), (title,)).fetchone()
            return _row_to_article(row) if row else None

    def search_stored(self, keyword: str, limit: int = 20) -> List[StoredArticle]:
        pattern = f"%{keyword}%"
        with self._connect() as conn:
            rows = conn.execute(
                self._parameters(
                    """
                    SELECT * FROM articles
                    WHERE title LIKE ? OR summary LIKE ? OR content LIKE ? OR categories LIKE ?
                    ORDER BY fetched_at DESC
                    LIMIT ?
                    """
                ),
                (pattern, pattern, pattern, pattern, limit),
            ).fetchall()
            return [_row_to_article(row) for row in rows]

    def retrieve(self, query: str, limit: int = 5) -> List[StoredArticle]:
        """Return stored articles containing at least one query term.

        Retrieval is intentionally dependency-free and works on both SQLite and
        Postgres. Ranking is applied in ResearchBot so the SQL layer stays portable.
        """
        terms = [term for term in query.split() if len(term) > 1]
        if not terms:
            return []
        clauses = []
        parameters = []
        for term in terms:
            pattern = f"%{term}%"
            clauses.append(
                "(LOWER(title) LIKE LOWER(?) OR LOWER(summary) LIKE LOWER(?) "
                "OR LOWER(content) LIKE LOWER(?) OR LOWER(categories) LIKE LOWER(?))"
            )
            parameters.extend([pattern] * 4)
        sql = f"SELECT * FROM articles WHERE {' OR '.join(clauses)} ORDER BY fetched_at DESC LIMIT ?"
        parameters.append(max(limit * 5, limit))
        with self._connect() as conn:
            rows = conn.execute(self._parameters(sql), parameters).fetchall()
            return [_row_to_article(row) for row in rows]

    def vector_search(self, embedding: List[float], limit: int = 5) -> List[StoredArticle]:
        """Find nearest stored articles using cosine distance."""
        if self.database_url:
            vector = "[" + ",".join(str(value) for value in embedding) + "]"
            with self._connect() as conn:
                rows = conn.execute(
                    """
                    SELECT a.*
                    FROM articles AS a
                    JOIN article_embeddings AS e ON e.article_id = a.id
                    ORDER BY e.embedding <=> %s::vector
                    LIMIT %s
                    """,
                    (vector, limit),
                ).fetchall()
                return [_row_to_article(row) for row in rows]

        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT a.*, e.embedding
                FROM articles AS a
                JOIN article_embeddings AS e ON e.article_id = a.id
                """
            ).fetchall()
        scored = []
        for row in rows:
            stored = json.loads(row["embedding"])
            scored.append((_cosine_similarity(embedding, stored), _row_to_article(row)))
        scored.sort(key=lambda item: item[0], reverse=True)
        return [article for _, article in scored[:limit]]

    def list_recent(self, limit: int = 10) -> List[StoredArticle]:
        with self._connect() as conn:
            rows = conn.execute(
                self._parameters(
                    "SELECT * FROM articles ORDER BY fetched_at DESC LIMIT ?"
                ),
                (limit,),
            ).fetchall()
            return [_row_to_article(row) for row in rows]

    def delete_article(self, page_id: int) -> bool:
        with self._connect() as conn:
            cursor = conn.execute(
                self._parameters("DELETE FROM articles WHERE page_id = ?"),
                (page_id,),
            )
            return cursor.rowcount > 0

    def count(self) -> int:
        with self._connect() as conn:
            row = conn.execute("SELECT COUNT(*) AS c FROM articles").fetchone()
            return row["c"]


def _row_to_article(row) -> StoredArticle:
    return StoredArticle(
        record_id=row["id"],
        page_id=row["page_id"],
        title=row["title"],
        summary=row["summary"] or "",
        content=row["content"] if "content" in row.keys() else row["summary"] or "",
        url=row["url"] or "",
        categories=json.loads(row["categories"] or "[]"),
        word_count=row["word_count"] or 0,
        source=row["source"] or "wikipedia",
        fetched_at=row["fetched_at"],
    )


def _cosine_similarity(left: List[float], right: List[float]) -> float:
    if len(left) != len(right):
        return -1.0
    left_norm = math.sqrt(sum(value * value for value in left))
    right_norm = math.sqrt(sum(value * value for value in right))
    if not left_norm or not right_norm:
        return -1.0
    return sum(a * b for a, b in zip(left, right)) / (left_norm * right_norm)